---
name: Architecture & design
about: Keep track of code design & architecture needs, allow it to be scheduled
title: "[AD}"
labels: ''
assignees: ''

---

** Description **
Describe the architectural change or design change that needs to be defined.

Note: the output must to be a design document, to be attached to the issue.
