name: Feature request
description: Suggest an idea for this project
title: "[NEW] "
labels: ["new feature"]
body:
  - type: input
    id: feature-description
    attributes:
      label: Feature headliner
      description: A short description of the feature
      placeholder: “As a [persona], I [want to], [so that].”
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: "List here what would make an implementation acceptable for this user story. Include everything you want done: functionality, documentation, localization, anything else."
      placeholder: "- there is a new control &#10;&#13;
                    - I can use the control for ... &#10;&#13;
                    - The control validates its content to ..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you want this feature, what is the ultimate goal? Where do you expect to start? What do you expect to do? What is the expected result? Are there any possible error cases, and how would you like them handled?
  - type: textarea
    id: suggested-implementation
    attributes:
      label: Suggested implementation
      description: Here you get to suggest an implementation. Note that this is a suggestion. It provides no guarantee that the final implementation will match your suggestion.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered and rejected
      description: "A clear and concise description of any alternative solutions or features you've considered (if any)."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
