name: User experience
description: Keep track of UxD issues
title: "[UxD] "
body:
  - type: textarea
    id: definition
    attributes:
      label: definition
      description: Describe the need that this UxD issue will cover. It can be as simple as referring to a new feature issue.
      placeholder: Make the text red and remove that button.
    validations:
      required: true

